/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author stefan
 */
public class DartGame extends javax.swing.JFrame {

    /**
     * Creates new form DartGame
     */
    public DartGame() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        board = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        player = new javax.swing.JPanel();
        checkout = new javax.swing.JPanel();
        throwvalue = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Format = new javax.swing.JMenu();
        f_301 = new javax.swing.JMenuItem();
        f_501 = new javax.swing.JMenuItem();
        Spieler = new javax.swing.JMenu();
        p_1 = new javax.swing.JMenuItem();
        p_2 = new javax.swing.JMenuItem();
        p_3 = new javax.swing.JMenuItem();
        p_4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        board.setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Board.jpg"))); // NOI18N
        background.setText("jLabel1");
        board.add(background);
        background.setBounds(0, 0, 880, 820);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(board, gridBagConstraints);

        player.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(player, gridBagConstraints);

        checkout.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(checkout, gridBagConstraints);

        throwvalue.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(throwvalue, gridBagConstraints);

        Format.setText("Format");

        f_301.setText("301 - Double out");
        Format.add(f_301);

        f_501.setText("501 - Double out");
        Format.add(f_501);

        jMenuBar1.add(Format);

        Spieler.setText("Spieler");

        p_1.setText("1 Spieler");
        Spieler.add(p_1);

        p_2.setText("2 Spieler");
        Spieler.add(p_2);

        p_3.setText("3 Spieler");
        Spieler.add(p_3);

        p_4.setText("4 Spieler");
        Spieler.add(p_4);

        jMenuBar1.add(Spieler);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DartGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Format;
    private javax.swing.JMenu Spieler;
    private javax.swing.JLabel background;
    private javax.swing.JPanel board;
    private javax.swing.JPanel checkout;
    private javax.swing.JMenuItem f_301;
    private javax.swing.JMenuItem f_501;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem p_1;
    private javax.swing.JMenuItem p_2;
    private javax.swing.JMenuItem p_3;
    private javax.swing.JMenuItem p_4;
    private javax.swing.JPanel player;
    private javax.swing.JPanel throwvalue;
    // End of variables declaration//GEN-END:variables
}
